version: "3.8"

services:
  frontend:
    build:
      context: .
      dockerfile: dev.dockerfile
    container_name: frontend
    restart: always
    ports: 
      - "4200:4200"
    volumes: 
      - ./:/app
      - node_modules:/node_modules
  
  backend:
    image: eskdev/consumet-api:latest
    ports:
      - "3000:3000"

  nginx:
    build: 
      context: ./nginx
      dockerfile: Dockerfile
    container_name: nginx
    restart: always
    ports: 
      - "80:80"
    links:
      - frontend
      - backend 

volumes:
    node_modules: {}